Repository raspberrypi/documentation, pull requests merged in 2019-11, with the labels that each got.

#1285 Update FAQ README.md
  faqs/README.md
Labels: requires technical check

#1230 Added note regarding zenity package requirement on Linux distributions
  installation/installing-images/README.md
Labels: requires technical check

#1204 Update overclocking.md
  configuration/config-txt/overclocking.md
Labels: requires technical check

#1189 Rewrite SD create on Mac: Use etcher or 1 example using dd
  installation/installing-images/mac.md
Labels: requires technical check

#1077 James h65 patch vcgencmd vcdbg tvservice docs
  raspbian/README.md
  raspbian/applications/README.md
  raspbian/applications/tvservice.md
  raspbian/applications/vcdbg.md
  raspbian/applications/vcgencmd.md
Labels: ready for copy-edit

#1010 Add a first draft of a NFS guide to the Pi repository
  configuration/README.md
  configuration/nfs.md
Labels: requires technical check

#917 Update linux.md - lsblk -p
  installation/installing-images/linux.md
Labels: Waiting internal comment

#1300 Updated app list for raspbian
  raspbian/applications/README.md
Labels: ready for copy-edit

#1248 Added details for Windows 10's «OpenSSH Client»
  remote-access/ssh/README.md
  remote-access/ssh/windows10.md
Labels: requires technical check

#1334 Andrums bootmode page fixups
  hardware/raspberrypi/bootmodes/msd.md
Labels: requires technical check

#1349 Small changes in copy-editing
  hardware/raspberrypi/bootmodes/bootflow.md
Labels: requires technical check
