Repository raspberrypi/documentation, pull requests merged in 2021-12, with the labels that each got.

#2307 Update bcm2711-bootloader.adoc
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
Labels: enhancement, ready to merge, documentation

#2281 Update overclocking.adoc
  documentation/asciidoc/computers/config_txt/overclocking.adoc
Labels: waiting for comment, documentation

#2308 Add cross-reference from boot_ramdisk to boot-folder-contents
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
Labels: documentation

#2311 Fix typo in `installing-from-mac.adoc`
  documentation/asciidoc/computers/getting-started/installing-from-mac.adoc
Labels: typo

#2313 Add build-time-check to catch Markdown-style links
  scripts/create_build_adoc.py
  scripts/create_build_adoc_include.py
Labels: toolchain

#2236 Accessibility and SEO improvements
  jekyll-assets/_includes/head.html
  jekyll-assets/_includes/header.html
  jekyll-assets/_layouts/boxes.html
  jekyll-assets/css/style.css
Labels: toolchain

#2326 Update configuring-networking.adoc
  documentation/asciidoc/computers/configuration/configuring-networking.adoc
Labels: typo
