Repository raspberrypi/documentation, pull requests merged in 2021-09, with the labels that each got.

#2123 Update graphics-utilities.adoc
  documentation/asciidoc/computers/os/graphics-utilities.adoc
Labels: enhancement

#2145 Adding copy-to-clipboard functionality
  Gemfile
  Gemfile.lock
  jekyll-assets/_includes/scripts.html
  jekyll-assets/_plugins/add_copy_to_clipboard_button.rb
  jekyll-assets/css/style.css
  jekyll-assets/scripts/clipboard.min.js
  jekyll-assets/scripts/copy-to-clipboard.js
  makefiles/jekyll.mk
Labels: enhancement, toolchain

#2130 Toggling scrollbar off for Windows
  jekyll-assets/css/style.css
Labels: bug fix, browser

#2142 Update securing-the-raspberry-pi.adoc
  documentation/asciidoc/computers/configuration/securing-the-raspberry-pi.adoc
Labels: documentation

#2149 Fix local 64-bit installation instructions
  documentation/asciidoc/computers/linux_kernel/building.adoc
Labels: documentation

#2152 Update copyright.html
  jekyll-assets/_includes/copyright.html
Labels: documentation

#2153 Adding classes for floats and widths
  documentation/asciidoc/microcontrollers/micropython/what-is-micropython.adoc
  jekyll-assets/css/style.css
Labels: enhancement, toolchain

#2154 Adding non-JS TOC
  jekyll-assets/_includes/nav.html
  jekyll-assets/css/style.css
  jekyll-assets/scripts/nav.js
Labels: enhancement, toolchain

#2156 Prevent extraneous HTML files being created
  makefiles/jekyll.mk
  makefiles/shared.ninja
  scripts/create_build_adoc.py
  scripts/create_jekyll_ninjabuild.py
Labels: bug fix, toolchain

#2160 Throw an error if a MarkDown-style header is accidentally used.
  scripts/create_build_adoc.py
  scripts/create_build_adoc_include.py
Labels: toolchain

#2159 Big refactoring of the toolchain
  .gitignore
  Makefile
  README.md
  _config.yml
  build.ninja
  makefiles/html.mk
  makefiles/jekyll.mk
  makefiles/shared.mk
  makefiles/shared.ninja
  makefiles/shared_vars.txt
  scripts/create_auto_ninjabuild.py
Labels: toolchain

#2165 Miscellaneous small camera documentation corrections
  documentation/asciidoc/accessories/camera/camera_usage.adoc
  documentation/asciidoc/accessories/camera/csi-2-usage.adoc
  documentation/asciidoc/accessories/camera/libcamera_options_still.adoc
Labels: documentation

#2166 Don't allow triple-backticks to be used for code-markup
  scripts/create_build_adoc.py
  scripts/create_build_adoc_include.py
Labels: toolchain

#2174 typo on title
  documentation/asciidoc/microcontrollers/raspberry-pi-pico/about_pico.adoc
Labels: typo

#2175 Update : How to check number of processors
  documentation/asciidoc/computers/linux_kernel/building.adoc
Labels: documentation

#2176 Update : Usage scp
  documentation/asciidoc/computers/remote-access/scp.adoc
Labels: documentation

#2162 New camera documentation
  documentation/asciidoc/accessories/camera.adoc
  documentation/asciidoc/accessories/camera/camera_hardware.adoc
  documentation/asciidoc/accessories/camera/camera_installing.adoc
  documentation/asciidoc/accessories/camera/camera_usage.adoc
  documentation/asciidoc/accessories/camera/csi-2-usage.adoc
  documentation/asciidoc/accessories/camera/gstreamer.adoc
  documentation/asciidoc/accessories/camera/images/annotate.jpg
  documentation/asciidoc/accessories/camera/images/classify.jpg
  documentation/asciidoc/accessories/camera/images/detection.jpg
  documentation/asciidoc/accessories/camera/images/drc.jpg
  documentation/asciidoc/accessories/camera/images/face_detect.jpg
  documentation/asciidoc/accessories/camera/images/focus.jpg
  documentation/asciidoc/accessories/camera/images/hdr.jpg
  documentation/asciidoc/accessories/camera/images/negate.jpg
  documentation/asciidoc/accessories/camera/images/nodrc.jpg
  documentation/asciidoc/accessories/camera/images/nohdr.jpg
  documentation/asciidoc/accessories/camera/images/pose.jpg
  documentation/asciidoc/accessories/camera/images/preview_window.jpg
  documentation/asciidoc/accessories/camera/images/segmentation.jpg
  documentation/asciidoc/accessories/camera/images/sobel.jpg
  documentation/asciidoc/accessories/camera/images/sobel_negate.jpg
  documentation/asciidoc/accessories/camera/libcamera_3rd_party_tuning.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_building.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_getting_help.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_getting_started.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_intro.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_post_processing.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_post_processing_opencv.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_post_processing_tflite.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_post_processing_writing.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_writing.adoc
  documentation/asciidoc/accessories/camera/libcamera_detect.adoc
  documentation/asciidoc/accessories/camera/libcamera_differences.adoc
  documentation/asciidoc/accessories/camera/libcamera_hello.adoc
  documentation/asciidoc/accessories/camera/libcamera_jpeg.adoc
  documentation/asciidoc/accessories/camera/libcamera_known_issues.adoc
  documentation/asciidoc/accessories/camera/libcamera_options_common.adoc
  documentation/asciidoc/accessories/camera/libcamera_options_still.adoc
  documentation/asciidoc/accessories/camera/libcamera_options_vid.adoc
  documentation/asciidoc/accessories/camera/libcamera_python.adoc
  documentation/asciidoc/accessories/camera/libcamera_raw.adoc
  documentation/asciidoc/accessories/camera/libcamera_still.adoc
  documentation/asciidoc/accessories/camera/libcamera_vid.adoc
  documentation/asciidoc/accessories/camera/longexp.adoc
  documentation/asciidoc/accessories/camera/raspicam.adoc
  documentation/asciidoc/accessories/camera/raw.adoc
  documentation/asciidoc/accessories/camera/timelapse.adoc
  documentation/asciidoc/accessories/camera/v4l2.adoc
Labels: enhancement, documentation

#2164 Update bootflow-2711.adoc - describe TRYBOOT
  documentation/asciidoc/computers/raspberry-pi/bootflow-2711.adoc
Labels: documentation

#2177 Security and other fixes
  Gemfile
  Gemfile.lock
Labels: toolchain
