Repository raspberrypi/documentation, pull requests merged in 2021-08, with the labels that each got.

#1966 Fix page titles
  makefiles/shared.ninja
  scripts/create_build_adoc.py
  scripts/create_jekyll_ninjabuild.py
Labels: toolchain

#1967 Update frequency-management.adoc
  documentation/asciidoc/computers/raspberry-pi/frequency-management.adoc
Labels: enhancement

#1969 Add opensocial image
  documentation/images/opensocial.png
  jekyll-assets/_includes/head.html
  makefiles/jekyll.mk
Labels: toolchain

#1975 Run the GitHub Actions build on pull requests
  .github/workflows/build.yml
Labels: toolchain

#1974 Update display-rotation.adoc
  documentation/asciidoc/computers/configuration/display-rotation.adoc
Labels: typo

#1971 Fix titles redux
  jekyll-assets/_includes/head.html
  scripts/create_build_adoc.py
  scripts/create_jekyll_ninjabuild.py
Labels: toolchain

#1980 Fix page titles - again again!
  jekyll-assets/_includes/head.html
  jekyll-assets/_layouts/docs.html
  scripts/create_build_adoc.py
  scripts/create_jekyll_ninjabuild.py
Labels: bug fix, toolchain

#1988 Typo
  documentation/asciidoc/computers/raspberry-pi/frequency-management.adoc
Labels: typo

#1989 Update boot.adoc
  documentation/asciidoc/computers/config_txt/boot.adoc
Labels: enhancement

#1993 Update conditional.adoc
  documentation/asciidoc/computers/config_txt/conditional.adoc
Labels: enhancement, documentation

#1994 Update index.json
  documentation/index.json
Labels: typo

#1997 Add extra flexibility to .htaccess
  documentation/htaccess_extra.txt
  makefiles/jekyll.mk
  makefiles/shared_vars.txt
  scripts/create_htaccess.py
Labels: enhancement, toolchain

#2006 Add redirect for libcamera PDF
  documentation/redirects/datasheets.csv
Labels: bug fix

#2008 Add redirects for all libcamera PDF versions
  documentation/redirects/datasheets.csv
Labels: bug fix

#1996 Update frequency-management.adoc
  documentation/asciidoc/computers/raspberry-pi/frequency-management.adoc
Labels: typo

#2012 Redirect compliance page to PIP
  documentation/htaccess_extra.txt
  scripts/create_htaccess.py
Labels: bug fix

#2015 Add redirects for Pi 4 mechanical drawings
  documentation/redirects/datasheets.csv
Labels: bug fix

#2018 Add redirects for moved PDFs
  documentation/redirects/datasheets.csv
Labels: bug fix

#2020 Don't run build twice for pull requests
  .github/workflows/build.yml
Labels: toolchain

#2001 Update spi-bus-on-raspberry-pi.adoc
  documentation/asciidoc/computers/raspberry-pi/spi-bus-on-raspberry-pi.adoc
Labels: copy edit

#2002 Update power-supplies.adoc
  documentation/asciidoc/computers/raspberry-pi/power-supplies.adoc
Labels: copy edit

#2004 Update boot-eeprom-rpi4.adoc
  documentation/asciidoc/computers/raspberry-pi/boot-eeprom-rpi4.adoc
Labels: copy edit

#2022 Update boot-nvme.adoc
  documentation/asciidoc/computers/raspberry-pi/boot-nvme.adoc
Labels: enhancement

#2027 Add some more redirects (and fix some broken ones)
  documentation/redirects/datasheets.csv
  scripts/create_htaccess.py
Labels: toolchain

#2046 Minor typo
  README.md
Labels: typo

#2044 Typo
  documentation/asciidoc/computers/remote-access/samba.adoc
Labels: typo

#2043 Typo
  documentation/asciidoc/computers/raspberry-pi/spi-bus-on-raspberry-pi.adoc
Labels: typo

#2042 Typo
  documentation/asciidoc/computers/raspberry-pi/otp-bits.adoc
Labels: typo

#2041 Typo
  documentation/asciidoc/computers/raspberry-pi/gpio-on-raspberry-pi.adoc
Labels: typo

#2040 Typo
  documentation/asciidoc/computers/raspberry-pi/display-parallel-interface.adoc
Labels: typo

#2039 Typo
  documentation/asciidoc/computers/raspberry-pi/bootflow-2711.adoc
Labels: typo

#2038 Typos
  documentation/asciidoc/computers/os/graphics-utilities.adoc
Labels: typo

#2036 Typo
  documentation/asciidoc/computers/configuration/raspi-config.adoc
Labels: typo

#2035 Typo
  documentation/asciidoc/computers/configuration/device-tree.adoc
Labels: typo

#2034 Typos
  documentation/asciidoc/computers/compute-module/cmio-camera.adoc
Labels: typo

#2033 Typo
  documentation/asciidoc/accessories/display/display_intro.adoc
Labels: typo

#2032 Typo
  documentation/asciidoc/accessories/camera/raspicam.adoc
Labels: typo

#2037 Typo
  documentation/asciidoc/computers/config_txt/overclocking.adoc
Labels: typo

#2030 Move under voltage detection away from CM4
  documentation/asciidoc/computers/compute-module/datasheet.adoc
Labels: documentation

#2045 Remove A0 reference to be consistent with other BCM2837 references
  documentation/asciidoc/computers/processors/bcm2837b0.adoc
Labels: copy edit

#2062 Fix syntax typo
  documentation/asciidoc/accessories/keyboard-and-mouse/getting-started-keyboard.adoc
Labels: typo

#2026 Add tooling to create a 404 page. Partially fixes #1976
  jekyll-assets/_includes/subtitle404.html
  jekyll-assets/_includes/toptitle404.html
  jekyll-assets/_layouts/boxes.html
  jekyll-assets/css/boxes.css
  scripts/create_jekyll_ninjabuild.py
Labels: toolchain

#2064 Adjusting alignment of copyright text
  jekyll-assets/css/style.css
Labels: bug fix

#2070 Fixes #2057
  scripts/create_jekyll_ninjabuild.py
Labels: bug fix, toolchain

#2058 Added list of RP2040-based boards.
  documentation/asciidoc/microcontrollers/rp2040.adoc
  documentation/asciidoc/microcontrollers/rp2040/images/arduino_nano.png
  documentation/asciidoc/microcontrollers/rp2040/images/feather-2040.jpg
  documentation/asciidoc/microcontrollers/rp2040/images/itsybitsy-2040.jpg
  documentation/asciidoc/microcontrollers/rp2040/images/keybow-2040.jpg
  documentation/asciidoc/microcontrollers/rp2040/images/micromod.jpg
  documentation/asciidoc/microcontrollers/rp2040/images/pga2040.jpg
  documentation/asciidoc/microcontrollers/rp2040/images/pico.jpg
  documentation/asciidoc/microcontrollers/rp2040/images/pico_lipo.jpg
  documentation/asciidoc/microcontrollers/rp2040/images/picosystem.jpg
  documentation/asciidoc/microcontrollers/rp2040/images/pro-micro.jpg
  documentation/asciidoc/microcontrollers/rp2040/images/thing-plus.jpg
  documentation/asciidoc/microcontrollers/rp2040/images/tiny-2040.jpg
  documentation/asciidoc/microcontrollers/rp2040/rp2040_based_boards.adoc
Labels: bug, documentation

#2073 Add instructions for building locally on 64bit
  documentation/asciidoc/computers/linux_kernel/building.adoc
Labels: enhancement, documentation

#2078 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: typo

#2082 secure-shell.adoc: grammar fix
  documentation/asciidoc/computers/configuration/headless.adoc
  documentation/asciidoc/computers/remote-access/secure-shell.adoc
Labels: typo

#2085 Update kernel-command-line-config.adoc
  documentation/asciidoc/computers/configuration/kernel-command-line-config.adoc
Labels: enhancement

#2092 Adding styles for the edit link
  jekyll-assets/_includes/github_edit.adoc
  jekyll-assets/css/style.css
Labels: enhancement

#2065 Add heading anchor links
  Gemfile
  jekyll-assets/css/style.css
  scripts/create_build_adoc.py
Labels: enhancement, in progress, toolchain

#2072 Add "Edit on GitHub" links to each page / section. Fixes #2029
  .github/workflows/build.yml
  _config.yml
  jekyll-assets/_includes/github_edit.adoc
  jekyll-assets/css/style.css
  makefiles/jekyll.mk
  makefiles/shared.ninja
  makefiles/shared_vars.txt
  requirements.txt
  scripts/create_build_adoc.py
  scripts/create_build_adoc_include.py
  scripts/create_jekyll_ninjabuild.py
Labels: enhancement, in progress, toolchain

#2107 Fix #2104
  documentation/asciidoc/computers/raspberry-pi/spi-bus-on-raspberry-pi.adoc
Labels: bug fix, documentation

#2108 prefix hex number with 0x
  documentation/asciidoc/computers/raspberry-pi/gpio-pad-controls.adoc
Labels: copy edit

#2090 Update revision-codes.adoc
  documentation/asciidoc/computers/raspberry-pi/revision-codes.adoc
Labels: copy edit

#2106 Update installing-from-an-image.adoc
  documentation/asciidoc/computers/getting-started/installing-from-an-image.adoc
Labels: copy edit

#2110 Update remote-access-introduction.adoc
  documentation/asciidoc/computers/remote-access/remote-access-introduction.adoc
Labels: typo

#2100 Ensure PRs based on master can only come from the develop branch
  .github/workflows/build.yml
Labels: toolchain, github

#2111 Typo
  documentation/asciidoc/computers/remote-access/remote-access-introduction.adoc
Labels: typo

#2113 Log the current branches with GitHub Actions
  .github/workflows/build.yml
Labels: bug fix

#2124 prefix numbers with base
  documentation/asciidoc/computers/raspberry-pi/gpio-pad-controls.adoc
Labels: copy edit

#2126 Remove SPI0 Alternate from CM4
  documentation/asciidoc/computers/raspberry-pi/spi-bus-on-raspberry-pi.adoc
Labels: feedback

#2129 Fixing paragraph margin for different styles of admonitions
  jekyll-assets/css/style.css
Labels: bug fix, toolchain

#2081 Fixes #1463
  documentation/asciidoc/computers/raspberry-pi/gpio-pad-controls.adoc
Labels: bug fix
