Repository raspberrypi/documentation, pull requests merged in 2021-06, with the labels that each got.

#1812 Update php5 and php7.0 references to php7.3
  remote-access/web-server/nginx.md
Labels: read to merge

#1819 Setup: remove reference to NOOBS
  setup/README.md
Labels: read to merge

#1848 Added instructions for switching off display power in response to #1780.
  configuration/screensaver.md
Labels: read to merge

#1698 Fix over_voltage description
  configuration/config-txt/overclocking.md
Labels: Waiting internal comment, read to merge

#1886 Add missing revision codes for CM4
  hardware/raspberrypi/revision-codes/README.md
Labels: Waiting internal comment

#1767 Additional / better example for supplicant file.
  configuration/wireless/headless.md
Labels: read to merge

#1739 Update samba.md
  remote-access/samba.md
Labels: Waiting internal comment, read to merge

#1817 Installation/sd-cards.md: trim down
  installation/sd-cards.md
Labels: read to merge

#1851 raspbian/applications/vcgencmd.md: various minor fixups
  raspbian/applications/vcgencmd.md
Labels: Waiting internal comment, read to merge

#1865 Update unix.md
  remote-access/ssh/unix.md
Labels: read to merge

#1879 Update led_blink_warnings.md
  configuration/led_blink_warnings.md
Labels: read to merge

#1703 updated the command sequence and location of the service file
  linux/usage/systemd.md
Labels: read to merge

#1554 Elaborated on HQ Camera gasket assembly
  hardware/camera/hqcam_filter_removal.md
  hardware/camera/rpi_hq_cam_clear_filter.jpg
  hardware/camera/rpi_hq_cam_gasket.jpg
  hardware/camera/rpi_hq_cam_ir_filter.jpg
  hardware/camera/rpi_hq_cam_sensor.jpg
Labels: read to merge

#1858 Fix note about uncompressed arm64 images
  configuration/config-txt/boot.md
Labels: read to merge

#1637 Explicitly call-out Vendor Class identifier for PXE
  hardware/raspberrypi/bootmodes/net.md
Labels: read to merge

#1912 Removed content that will be unsupported going forward.
  usage/README.md
  usage/demos/README.md
  usage/demos/hello-audio.md
  usage/demos/hello-fractal.md
  usage/demos/hello-teapot.md
  usage/demos/hello-triangle.md
  usage/demos/hello-video.md
  usage/demos/hello-world.md
  usage/demos/images/bbb.jpg
  usage/demos/images/mandelbrot.jpg
  usage/demos/images/teapot.jpg
  usage/gpio-plus-and-raspi2/README.md
  usage/kodi/README.md
  usage/kodi/images/openelec-main.png
  usage/kodi/images/openelec.png
  usage/kodi/images/xbmc-youtube.jpg
  usage/mathematica/README.md
  usage/minecraft/README.md
  usage/minecraft/images/minecraft-pi-banner.png
  usage/python-games/README.md
  usage/python-games/images/app-menu-python-games.png
  usage/python-games/images/audio-output.png
  usage/python-games/images/flippy.png
  usage/python-games/images/four-in-a-row-code.png
  usage/python-games/images/four-in-a-row.png
  usage/python-games/images/python-games-folder.png
  usage/python-games/images/python-games-selection.png
  usage/python-games/images/python-games-terminal.png
  usage/python-games/images/sonic-pi.png
  usage/scratch/README.md
  usage/scratch/gpio/README.md
  usage/sonic-pi/README.md
  usage/wordpress/README.md
  usage/xbmc/README.md
Labels: read to merge

#1869 Link camera page to libcamera page
  hardware/camera/README.md
Labels: read to merge

#1901 Add disable_poe_fan to config.txt documentation
  configuration/config-txt/boot.md
  configuration/config-txt/misc.md
Labels: read to merge

#1775 Update net_tutorial.md to allow DNS server to be used for internal systems.
  hardware/raspberrypi/bootmodes/net_tutorial.md
Labels: read to merge

#1878 Update overclocking.md
  configuration/config-txt/overclocking.md
Labels: in progress

#1887 Update hardware/raspberrypi/usb/README.md
  hardware/raspberrypi/usb/README.md
Labels: read to merge

#1918 Update camera timelapse video creation
  usage/camera/raspicam/timelapse.md
Labels: bug, ready to merge

#1322 Update ip-address.md
  remote-access/ip-address.md
Labels: ready to merge

#1847 Added peripheral address for BCM2711 in response to #1771
  hardware/raspberrypi/peripheral_addresses.md
Labels: ready to merge

#1318 Hints for use with IPv6 added
  remote-access/access-over-Internet/README.md
Labels: ready to merge
