Repository raspberrypi/documentation, pull requests merged in 2021-07, with the labels that each got.

#1932 Update timelapse.md
  usage/camera/raspicam/timelapse.md
Labels: in progress

#1941 explain how [pi400]/[cm4] conditional filters interact with [pi4]
  configuration/config-txt/conditional.md
Labels: enhancement

#1942 Fixup net_tutorial.md
  hardware/raspberrypi/bootmodes/net_tutorial.md
Labels: alternate #1930, enhancement

#1850 configuration/UART.md - minor simplifications
  configuration/uart.md
Labels: alternate #1849, ready to merge

#1943 Tidy up change from #1941
  configuration/config-txt/conditional.md
Labels: enhancement, ready to merge

#1947 Move the DTS and BIN files
  hardware/computemodule/cm-peri-sw-guide.md
  hardware/computemodule/cmio-camera.md
  hardware/computemodule/cmio-display.md
  hardware/computemodule/dt-blob-cam1.bin
  hardware/computemodule/dt-blob-cam1.dts
  hardware/computemodule/dt-blob-disp0-only.bin
  hardware/computemodule/dt-blob-disp0-only.dts
  hardware/computemodule/dt-blob-disp1-cam1.bin
  hardware/computemodule/dt-blob-disp1-cam1.dts
  hardware/computemodule/dt-blob-disp1-cam2.bin
  hardware/computemodule/dt-blob-disp1-cam2.dts
  hardware/computemodule/dt-blob-disp1-only.bin
  hardware/computemodule/dt-blob-disp1-only.dts
  hardware/computemodule/dt-blob-dualcam.bin
  hardware/computemodule/dt-blob-dualcam.dts
  hardware/computemodule/example1-overlay.dts
  hardware/computemodule/minimal-cm-dt-blob.dts
Labels: waiting
