Repository raspberrypi/documentation, pull requests merged in 2022-03, with the labels that each got.

#2452 Access-point-routed.adoc : add private IP address range
  documentation/asciidoc/computers/configuration/access-point-routed.adoc
Labels: documentation

#2453 Access-point-routed.adoc : keep consistency
  documentation/asciidoc/computers/configuration/access-point-routed.adoc
Labels: copy edit

#2455 Headless.adoc, net-motors.adoc update
  documentation/asciidoc/accessories/build-hat/net-motors.adoc
  documentation/asciidoc/computers/configuration/headless.adoc
Labels: typo

#2443 Fix Python sensors sample
  documentation/asciidoc/accessories/build-hat/py-sensors.adoc
Labels: bug, requires technical check

#2461 Split table into two for Pi4B and non Pi4B , simplify table as well
  documentation/asciidoc/computers/raspberry-pi/gpio-on-raspberry-pi.adoc
Labels: enhancement, documentation

#2460 Boot-msd.adoc : peel off the sentence
  documentation/asciidoc/computers/raspberry-pi/boot-msd.adoc
Labels: copy edit

#2463 Update for 2711 remove 3V3 (*** NB
  documentation/asciidoc/computers/raspberry-pi/gpio-pad-controls.adoc
Labels: documentation

#2464 Insert missing space
  documentation/asciidoc/computers/raspberry-pi/gpio-pad-controls.adoc
Labels: typo

#2465 Cmio-camera.adoc : insert Raspberry word
  documentation/asciidoc/computers/compute-module/cmio-camera.adoc
Labels: copy edit

#2468 Tv-hat.adoc : inline sentence
  documentation/asciidoc/accessories/tv-hat.adoc
Labels: copy edit

#2469 Tv-hat.adoc : putting on the highlight
  documentation/asciidoc/accessories/tv-hat.adoc
Labels: copy edit

#2470 Support Asciidoctor table alignment operators
  jekyll-assets/_includes/head.html
  jekyll-assets/css/style.css
Labels: toolchain

#2466 Textify table images
  documentation/asciidoc/computers/raspberry-pi/display-parallel-interface.adoc
Labels: documentation, accessibility

#2472 Display-parallel-interface.adoc : remove on the new version(#2466)
  documentation/asciidoc/computers/raspberry-pi/images/dpi-altfn2.png
  documentation/asciidoc/computers/raspberry-pi/images/dpi-packing.png
Labels: documentation

#2473 Remove outdated sentences
  documentation/asciidoc/computers/raspberry-pi/bootmodes.adoc
Labels: bug fix, documentation

#2477 Boot.adoc : insert Raspberry word
  documentation/asciidoc/computers/config_txt/boot.adoc
Labels: copy edit

#2481 Fixed typo in access-point-routed.adoc
  documentation/asciidoc/computers/configuration/access-point-routed.adoc
Labels: typo

#2485 Net install and HTTP boot configuration
  documentation/asciidoc/computers/getting-started/network-installation.adoc
  documentation/asciidoc/computers/raspberry-pi.adoc
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
  documentation/asciidoc/computers/raspberry-pi/boot-http.adoc
Labels: enhancement, ready to merge, documentation

#2488 Bcm2711-bootloader.adoc : update highlight mark and Raspberry Pi 4 USB description
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
Labels: copy edit

#2489 Remove abbreviation
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
Labels: copy edit

#2492 Update to the latest header
  jekyll-assets/_includes/header.html
Labels: toolchain

#2497 Corrected spelling mistake in documentation of connecting-a-monitor.adoc
  documentation/asciidoc/computers/getting-started/connecting-a-monitor.adoc
Labels: typo

#2498 Typos
  documentation/asciidoc/computers/configuration/configuring-networking.adoc
Labels: typo
