Repository raspberrypi/documentation, pull requests merged in 2022-04, with the labels that each got.

#2502 Configuring.adoc : typo
  documentation/asciidoc/computers/getting-started/configuring.adoc
Labels: typo

#2509 Added the rev1.5 Pi4's
  documentation/asciidoc/computers/raspberry-pi/revision-codes.adoc
Labels: enhancement, documentation

#2516 Remove errant space
  documentation/asciidoc/computers/using_linux/linux-bash.adoc
Labels: typo

#2521 computers/processors/bcm2835: fix dead links
  documentation/asciidoc/computers/processors/bcm2835.adoc
Labels: bug fix
