Repository raspberrypi/documentation, pull requests merged in 2022-01, with the labels that each got.

#2328 Update id reference
  documentation/asciidoc/computers/remote-access/scp.adoc
Labels: typo

#2335 Secure-shell.adoc : Fixed old-id
  documentation/asciidoc/computers/remote-access/secure-shell.adoc
Labels: typo

#2336 remote-access-introduction.adoc : Fixed small typo
  documentation/asciidoc/computers/remote-access/remote-access-introduction.adoc
Labels: typo

#2340 Add Jobs link to the site footer
  jekyll-assets/_includes/footer.html
Labels: toolchain

#2343 Fix pose_estimation_tf.json syntax errors
  documentation/asciidoc/accessories/camera/libcamera_apps_post_processing_tflite.adoc
Labels: documentation, camera 📷

#2344 fixed transposed device IDs (Issue #2339)
  documentation/asciidoc/accessories/build-hat/compat.adoc
Labels: documentation, lego 🧱

#2345 Check that all internal links and anchors are valid. Fixes #2332
  documentation/asciidoc/accessories/build-hat/preparing-build-hat.adoc
  documentation/asciidoc/accessories/camera/camera_usage.adoc
  documentation/asciidoc/accessories/camera/libcamera_detect.adoc
  documentation/asciidoc/computers/config_txt/common.adoc
  documentation/asciidoc/computers/configuration/headless.adoc
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
  documentation/asciidoc/computers/remote-access/secure-shell.adoc
  documentation/asciidoc/computers/remote-access/vnc.adoc
  scripts/create_nav.py
Labels: toolchain

#2346 Clarify build instructions
  README.md
Labels: toolchain

#2347 gumbo-parser not needed on Linux
  README.md
Labels: toolchain

#2348 Typo in example command
  documentation/asciidoc/accessories/camera/libcamera_vid.adoc
Labels: documentation, camera 📷

#2350 network-boot-raspberry-pi.adoc : typo
  documentation/asciidoc/computers/remote-access/network-boot-raspberry-pi.adoc
Labels: typo

#2353 Update NVMe documentation
  documentation/asciidoc/computers/raspberry-pi/boot-nvme.adoc
Labels: documentation

#2354 correct typo
  documentation/asciidoc/accessories/build-hat/introduction.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_getting_help.adoc
  documentation/asciidoc/computers/config_txt/video.adoc
  documentation/asciidoc/computers/raspberry-pi/spi-bus-on-raspberry-pi.adoc
  documentation/asciidoc/microcontrollers/micropython/what-is-micropython.adoc
Labels: typo

#2355 Fix typo in documentation
  documentation/asciidoc/microcontrollers/rp2040/technical_specification.adoc
Labels: typo

#2356 libcamera_apps_post_processing_writing.adoc : Update applications
  documentation/asciidoc/accessories/camera/libcamera_apps_post_processing_writing.adoc
Labels: typo

#2357 Camera documentation updates
  documentation/asciidoc/accessories/camera.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_multicam.adoc
  documentation/asciidoc/accessories/camera/libcamera_known_issues.adoc
  documentation/asciidoc/accessories/camera/libcamera_options_common.adoc
Labels: documentation, camera 📷

#2358 camera: Updates for the imminent updated Bullseye release
  documentation/asciidoc/accessories/camera/camera_usage.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_building.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_getting_started.adoc
  documentation/asciidoc/accessories/camera/libcamera_options_common.adoc
  documentation/asciidoc/accessories/camera/libcamera_options_still.adoc
  documentation/asciidoc/accessories/camera/libcamera_options_vid.adoc
Labels: documentation, camera 📷

#2365 Update cm-emmc-flashing.adoc
  documentation/asciidoc/computers/compute-module/cm-emmc-flashing.adoc
Labels: documentation

#2368 accessories/camera : correct words
  documentation/asciidoc/accessories/camera/libcamera_options_common.adoc
  documentation/asciidoc/accessories/camera/libcamera_options_still.adoc
Labels: typo

#2369 Mention the Raspberry Pi 400
  documentation/asciidoc/computers/processors/bcm2711.adoc
Labels: documentation

#2367 boot_folder.doc: Add important note about lscpu usage on Pi
  documentation/asciidoc/computers/configuration/boot_folder.adoc
Labels: enhancement, documentation

#2370 Update details of which Raspberry Pis use which processors
  documentation/asciidoc/computers/processors/bcm2711.adoc
  documentation/asciidoc/computers/processors/bcm2835.adoc
  documentation/asciidoc/computers/processors/bcm2837.adoc
  documentation/asciidoc/computers/processors/bcm2837b0.adoc
Labels: enhancement, documentation

#2374 Fix grammar typo
  documentation/asciidoc/computers/processors/bcm2835.adoc
Labels: typo

#2375 Reword awkward sentence
  documentation/asciidoc/accessories/camera/camera_hardware.adoc
Labels: documentation, copy edit

#2376 accessories/camera/ : small typo
  documentation/asciidoc/accessories/camera/libcamera_apps_post_processing.adoc
Labels: typo

#2380 accessories/camera : correct spelling on parameters
  documentation/asciidoc/accessories/camera/libcamera_apps_post_processing.adoc
Labels: typo

#2381 Update kernel build instructions
  documentation/asciidoc/computers/linux_kernel/building.adoc
Labels: documentation

#2382 computers/raspberry-pi : correct grammar
  documentation/asciidoc/computers/raspberry-pi/boot-net.adoc
Labels: typo

#2384 libcamera_apps_writing.adoc : correct some typo
  documentation/asciidoc/accessories/camera/libcamera_apps_writing.adoc
Labels: typo

#2386 computers/configuration/boot_folder.adoc : update kernel files part
  documentation/asciidoc/computers/configuration/boot_folder.adoc
Labels: documentation

#2387 computers/configuration/boot_folder.adoc : update kernel files part
  documentation/asciidoc/computers/configuration/boot_folder.adoc
Labels: documentation
