Repository raspberrypi/documentation, pull requests merged in 2022-02, with the labels that each got.

#2388 computers/raspberry-pi/boot-msd.adoc : fixed typo
  documentation/asciidoc/computers/raspberry-pi/boot-msd.adoc
Labels: typo

#2333 Replace Simple Jekyll Search with Algolia DocSearch
  build.ninja
  jekyll-assets/_includes/head.html
  jekyll-assets/_includes/search.html
  jekyll-assets/_includes/toptitle.html
  jekyll-assets/_includes/toptitle404.html
  jekyll-assets/css/style.css
  jekyll-assets/scripts/simple-jekyll-search.min.js
  scripts/create_auto_ninjabuild.py
  scripts/create_search.py
Labels: toolchain, either/or

#2393 CONTRIBUTING.md : add comma on words
  CONTRIBUTING.md
Labels: copy edit

#2403 asciidoc/accessories/camera/csi-2-usage.adoc : some correct
  documentation/asciidoc/accessories/camera/csi-2-usage.adoc
Labels: typo

#2404 accessories/camera/libcamera_hello.adoc : correct spelling on preceded
  documentation/asciidoc/accessories/camera/libcamera_hello.adoc
Labels: typo

#2361 Part numbers for small angular motor and 3x3 LED
  documentation/asciidoc/accessories/build-hat/compat.adoc
Labels: documentation, lego 🧱

#2377 Update compat.adoc - added aditional item numbers
  documentation/asciidoc/accessories/build-hat/compat.adoc
Labels: documentation, lego 🧱

#2406 correct name Pi Zero 2 W
  documentation/asciidoc/computers/getting-started/sd-cards.adoc
  documentation/asciidoc/computers/linux_kernel/building.adoc
  documentation/asciidoc/computers/raspberry-pi/boot-msd.adoc
  documentation/asciidoc/computers/raspberry-pi/raspberry-pi-schematics.adoc
Labels: copy edit

#2402 Adding .NET support
  documentation/asciidoc/accessories/build-hat.adoc
  documentation/asciidoc/accessories/build-hat/compat.adoc
  documentation/asciidoc/accessories/build-hat/images/3x3matrix.png
  documentation/asciidoc/accessories/build-hat/images/active-motor.png
  documentation/asciidoc/accessories/build-hat/images/color-distance.png
  documentation/asciidoc/accessories/build-hat/images/passive-light.png
  documentation/asciidoc/accessories/build-hat/images/spike-color.png
  documentation/asciidoc/accessories/build-hat/images/spike-distance.png
  documentation/asciidoc/accessories/build-hat/images/spike-force.png
  documentation/asciidoc/accessories/build-hat/images/train-motor.png
  documentation/asciidoc/accessories/build-hat/images/wedo-distance.png
  documentation/asciidoc/accessories/build-hat/images/wedo-tilt.png
  documentation/asciidoc/accessories/build-hat/links-to-other.adoc
  documentation/asciidoc/accessories/build-hat/net-brick.adoc
  documentation/asciidoc/accessories/build-hat/net-installing-software.adoc
  documentation/asciidoc/accessories/build-hat/net-motors.adoc
  documentation/asciidoc/accessories/build-hat/net-sensors.adoc
  documentation/asciidoc/accessories/build-hat/preparing-build-hat.adoc
  documentation/asciidoc/accessories/build-hat/py-installing-software.adoc
  documentation/asciidoc/accessories/build-hat/py-motors.adoc
  documentation/asciidoc/accessories/build-hat/py-sensors.adoc
  documentation/asciidoc/computers/getting-started.adoc
Labels: documentation, lego 🧱

#2412 Device-tree.adoc : correct model name
  documentation/asciidoc/computers/configuration/device-tree.adoc
Labels: copy edit

#2413 Fix minor typo in network-installation
  documentation/asciidoc/computers/getting-started/network-installation.adoc
Labels: typo

#2415 boot-gpio.adoc : fixed typo
  documentation/asciidoc/computers/raspberry-pi/boot-gpio.adoc
Labels: typo

#2416 bootflow-2711.adoc : correct spelling on firmware
  documentation/asciidoc/computers/raspberry-pi/bootflow-2711.adoc
Labels: typo

#2417 Grammar typo
  documentation/asciidoc/computers/raspberry-pi/bootflow-2711.adoc
Labels: typo

#2419 setting-up.adoc : correct indefinite article on appropriate
  documentation/asciidoc/computers/getting-started/setting-up.adoc
Labels: typo

#2418 Grammar typo
  documentation/asciidoc/computers/getting-started/network-installation.adoc
Labels: typo

#2426 Fix spelling mistakes found by codespell
  CONTRIBUTING.md
  documentation/asciidoc/accessories/build-hat/net-brick.adoc
  documentation/asciidoc/accessories/build-hat/net-sensors.adoc
  documentation/asciidoc/accessories/camera/libcamera_3rd_party_tuning.adoc
  documentation/asciidoc/accessories/camera/libcamera_apps_intro.adoc
  documentation/asciidoc/accessories/camera/libcamera_options_vid.adoc
  documentation/asciidoc/accessories/camera/libcamera_vid.adoc
  documentation/asciidoc/accessories/display/display_intro.adoc
  documentation/asciidoc/computers/config_txt/video.adoc
  documentation/asciidoc/computers/configuration/access-point-routed.adoc
  documentation/asciidoc/computers/raspberry-pi/display-parallel-interface.adoc
  documentation/asciidoc/computers/raspberry-pi/usb-bus-on-raspberry-pi.adoc
  documentation/asciidoc/microcontrollers/microcontroller_docs.adoc
Labels: copy edit

#2430 Raspberry-pi-industrial.adoc : remove duplicated words
  documentation/asciidoc/computers/raspberry-pi/raspberry-pi-industrial.adoc
Labels: typo

#2428 Various tweaks and tidyups to kernel-building instructions
  documentation/asciidoc/computers/linux_kernel/building.adoc
Labels: documentation, copy edit

#2427 Add minimum timeout values
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
Labels: enhancement, ready to merge, documentation

#2421 Update references to rpi-update to official location
  documentation/asciidoc/computers/os/updating.adoc
Labels: documentation

#2407 UART docs: Add CM3 and CM3+ default UART assignments
  documentation/asciidoc/computers/configuration/uart.adoc
Labels: enhancement, documentation

#2423 Power-supplies.adoc : update power supply device list
  documentation/asciidoc/computers/raspberry-pi/power-supplies.adoc
Labels: enhancement, needs discussion, documentation

#2429 Usb-bus-on-raspberry-pi.adoc : correct indefinite article on problem
  documentation/asciidoc/computers/raspberry-pi/usb-bus-on-raspberry-pi.adoc
Labels: typo

#2432 small typo
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
Labels: typo

#2433 Overclocking defaults changes
  documentation/asciidoc/computers/config_txt/overclocking.adoc
Labels: ready to merge, documentation

#2436 Add RPi Zero 2 W overclocking defaults
  documentation/asciidoc/computers/config_txt/overclocking.adoc
Labels: requires technical check, documentation

#2446 Bootflow-legacy.adoc : add space
  documentation/asciidoc/computers/configuration/raspi-config.adoc
  documentation/asciidoc/computers/raspberry-pi/bootflow-legacy.adoc
Labels: typo

#2445 Remove duplicated words
  documentation/asciidoc/accessories/camera/libcamera_apps_post_processing_writing.adoc
  documentation/asciidoc/computers/config_txt/camera.adoc
  documentation/asciidoc/computers/processors/rp3a0.adoc
Labels: typo

#2442 About-kernel.adoc : add "Raspberry" word
  documentation/asciidoc/computers/linux_kernel/about-kernel.adoc
Labels: copy edit

#2441 Minor : Fix Build HAT Python docs: "while" is not capitalized
  documentation/asciidoc/accessories/build-hat/py-motors.adoc
Labels: typo

#2439 Boot.adoc : update kernel part
  documentation/asciidoc/computers/config_txt/boot.adoc
Labels: copy edit

#2447 Bcm2711-bootloader.adoc : insert spacing on Pi 4
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
Labels: typo

#2440 Clarify extra pins on the 7" display.
  documentation/asciidoc/accessories/display/display_intro.adoc
  documentation/asciidoc/accessories/display/legacy.adoc
Labels: enhancement, documentation

#2449 Libcamera_apps_getting_started.adoc : capital change
  documentation/asciidoc/accessories/camera/libcamera_apps_getting_started.adoc
Labels: copy edit
