Repository raspberrypi/documentation, pull requests merged in 2023-03, with the labels that each got.

#2813 Add more information on using revision codes including code snippets …
  documentation/asciidoc/computers/raspberry-pi/revision-codes.adoc
Labels: enhancement, documentation

#2817 Tech- and copy-edit
  documentation/asciidoc/computers/raspberry-pi/revision-codes.adoc
Labels: copy edit

#2819 Remove extraneous 'and'
  documentation/asciidoc/microcontrollers/rp2040/rp2040_based_boards.adoc
Labels: copy edit

#2821 punctuation errors and wordy sentences
  documentation/asciidoc/computers/getting-started/setting-up.adoc
Labels: copy edit

#2822 punctuation error
  documentation/asciidoc/computers/os/rpi-os-introduction.adoc
Labels: typo

#2774 Fixes typo from ./asoundrc to .asoundrc
  documentation/asciidoc/accessories/audio/configuration.adoc
Labels: typo, audio 🔊

#2826 Typos
  documentation/asciidoc/accessories/camera/camera_hardware.adoc
Labels: typo

#2833 Update footer
  jekyll-assets/_includes/footer.html
Labels: toolchain

#2832 Add explanation of datetime options in libcamera apps post processing using opencv_annotate stage
  documentation/asciidoc/computers/camera/libcamera_apps_post_processing_opencv.adoc
Labels: enhancement, documentation, camera 📷

#2842 Typo
  documentation/asciidoc/computers/camera/camera_usage.adoc
Labels: typo

#2840 Typo
  documentation/asciidoc/accessories/audio/update-firmware.adoc
Labels: typo

#2839 Missing word ?
  documentation/asciidoc/microcontrollers/debug-probe/uart-connection.adoc
Labels: typo

#2837 Typos
  documentation/asciidoc/microcontrollers/debug-probe/installing-tools.adoc
Labels: typo

#2838 Remove duplicated "chapter"
  documentation/asciidoc/microcontrollers/debug-probe/swd-connection.adoc
Labels: typo

#2847 Hide email obfuscator spans
  jekyll-assets/css/style.css
Labels: bug fix, doxygen

#2851 GS Camera Launch
  documentation/asciidoc/accessories/camera.adoc
  documentation/asciidoc/accessories/camera/camera_hardware.adoc
  documentation/asciidoc/accessories/camera/filters.adoc
  documentation/asciidoc/accessories/camera/images/gs-camera.jpg
  documentation/asciidoc/computers/camera/camera_usage.adoc
  documentation/asciidoc/computers/camera/raspicam.adoc
  documentation/asciidoc/computers/config_txt/camera.adoc
  documentation/asciidoc/computers/os/using-webcams.adoc
Labels: enhancement, documentation

#2856 Typo
  documentation/asciidoc/accessories/camera/camera_hardware.adoc
Labels: typo

#2861 Typos
  documentation/asciidoc/accessories/camera/filters.adoc
Labels: typo, camera 📷

#2864 Fix copy-to-clipboard for doxygen code blocks
  jekyll-assets/scripts/copy-to-clipboard.js
Labels: bug fix, toolchain

#2827 Documentation for raspi-config command line interface
  documentation/asciidoc/computers/configuration/raspi-config.adoc
Labels: enhancement, documentation

#2865 Fix nav anchor handling
  scripts/transform_doxygen_html.py
Labels: bug fix

#2866 Hide sass deprecation warnings until minima release
  _config.yml
Labels: bug fix

#2868 Remove Wireframe and Custom PC from the footer
  jekyll-assets/_includes/footer.html
Labels: toolchain

#2870 Add missing documentation for USB_MSD_STARTUP_DELAY
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
Labels: enhancement, documentation

#2872 Typo
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
Labels: typo

#2877 Using flexbox for tabs to accomadate more tabs
  jekyll-assets/css/boxes.css
  jekyll-assets/css/tabs.css
Labels: enhancement, toolchain

#2873 Documentation of Raspberry Pi ID service
  documentation/asciidoc/services/id.adoc
  documentation/asciidoc/services/id/2fa.adoc
  documentation/asciidoc/services/id/images/auth_app.png
  documentation/asciidoc/services/id/images/authenticate.png
  documentation/asciidoc/services/id/images/create_account_identity.png
  documentation/asciidoc/services/id/images/enable_2fa.png
  documentation/asciidoc/services/id/images/id_2fa.png
  documentation/asciidoc/services/id/images/sign_in_identity.png
  documentation/asciidoc/services/id/images/signed_in_identity.png
  documentation/asciidoc/services/id/images/totp_enabled.png
  documentation/asciidoc/services/id/images/verify_identity.png
  documentation/asciidoc/services/id/signing_up.adoc
  documentation/index.json
  jekyll-assets/css/boxes.css
  jekyll-assets/css/tabs.css
Labels: enhancement, documentation

#2878 Update microcontroller_docs.adoc
  documentation/asciidoc/microcontrollers/microcontroller_docs.adoc
Labels: documentation

#2881 Update arm_64bit documentation to match reality
  documentation/asciidoc/computers/config_txt/boot.adoc
Labels: documentation

#2883 boot.adoc tweaks
  documentation/asciidoc/computers/config_txt/boot.adoc
Labels: documentation

#2886 Add Note for Hooking up SWD Pins on Non-H Raspberry Pi Pico Boards to Debug Probe
  documentation/asciidoc/microcontrollers/debug-probe/getting-started.adoc
Labels: enhancement, documentation

#2887 Typos
  documentation/asciidoc/microcontrollers/debug-probe/getting-started.adoc
Labels: typo
