Repository raspberrypi/documentation, pull requests merged in 2023-11, with the labels that each got.

#3261 Update site footer
  jekyll-assets/_includes/footer.html
Labels: toolchain

#3264 Adding max-width for floated images
  jekyll-assets/css/style.css
Labels: toolchain

#3269 Trim down 'get back to safety' instructions
  documentation/asciidoc/computers/os/updating.adoc
Labels: bug fix, documentation

#3271 Update introduction.adoc - fix typo
  documentation/asciidoc/computers/raspberry-pi-5/introduction.adoc
Labels: typo

#3278 Deploy to primary and secondary web servers
  .github/actions/deploy-action/action.yml
  .github/workflows/build.yml
Labels: toolchain

#3281 camera: Fix wrong package name for installation instructions
  documentation/asciidoc/computers/camera/rpicam_apps_building.adoc
Labels: bug fix, camera 📷

#3282 Fix broken Bullseye note on reverting to the latest stable release
  documentation/asciidoc/computers/os/updating.adoc
Labels: bug fix

#3273 GS Camera external trigger: fix for #3237
  documentation/asciidoc/accessories/camera/external_trigger.adoc
  documentation/asciidoc/accessories/camera/images/pico_wiring.jpg
  documentation/asciidoc/accessories/camera/images/synchronous_camera_wiring.jpg
  documentation/asciidoc/accessories/camera/synchronous_cameras.adoc
Labels: bug fix, documentation, camera 📷

#3265 Add notes about self-update on CM4
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
Labels: enhancement, documentation

#3284 Add Pi 5 instructions for building the kernel
  documentation/asciidoc/computers/linux_kernel/building.adoc
Labels: enhancement, documentation

#3287 Small edits for style and consistency
  documentation/asciidoc/computers/remote-access/find-your-ip-address.adoc
Labels: copy edit

#3291 getting-started: Imager button label correction
  documentation/asciidoc/computers/getting-started/install.adoc
Labels: bug fix

#3293 Rework TOC generation for doxygen docs
  scripts/create_build_adoc_doxygen.py
  scripts/create_output_index_json.py
  scripts/transform_doxygen_html.py
Labels: bug fix, toolchain

#3267 Moved rpi_power_supply + Fixed typo
  documentation/asciidoc/computers/configuration/device-tree.adoc
Labels: documentation

#3297 Fix parameter typo in rpicam-apps doc
  documentation/asciidoc/computers/camera/rpicam_apps_post_processing.adoc
Labels: typo

#3294 Update UART documentation for Raspberry Pi 5
  documentation/asciidoc/computers/configuration/uart.adoc
Labels: enhancement, documentation, pi5 5️⃣

#3301 Update installing-tools.adoc to fix ./bootstrap issue
  documentation/asciidoc/microcontrollers/debug-probe/installing-tools.adoc
Labels: documentation, rp2040

#3299 Removed leftover partial sentence + added some punctuation.
  documentation/asciidoc/computers/raspberry-pi-5/introduction.adoc
Labels: copy edit
