Repository raspberrypi/documentation, pull requests merged in 2023-09, with the labels that each got.

#3045 Removing ruby version requirement from README
  README.md
Labels: documentation

#3097 Bust cache for CSS and JS on every build
  jekyll-assets/_includes/head.html
  jekyll-assets/_includes/scripts.html
Labels: enhancement, toolchain

#3093 camera: Fix maximum exposure time value for Camera v1
  documentation/asciidoc/accessories/camera/camera_hardware.adoc
Labels: paused, bug fix, documentation, camera 📷, bookworm 🐛

#3104 Check for <<>>-style links
  scripts/create_nav.py
Labels: bug fix

#3107 Fixed last remaining boot partition mentions
  documentation/asciidoc/computers/compute-module/cm-peri-sw-guide.adoc
  documentation/asciidoc/computers/configuration/boot_folder.adoc
  documentation/asciidoc/computers/configuration/device-tree.adoc
  documentation/asciidoc/computers/configuration/external-storage.adoc
  documentation/asciidoc/computers/raspberry-pi/boot-nvme.adoc
  documentation/asciidoc/computers/remote-access/network-boot-raspberry-pi.adoc
Labels: bookworm 🐛

#3109 Updating screenshots and adding new ones
  documentation/asciidoc/accessories/audio/images/gui.png
  documentation/asciidoc/accessories/build-hat/images/raspi-config-2.png
  documentation/asciidoc/accessories/build-hat/images/setting-up.png
  documentation/asciidoc/computers/configuration/images/key.png
  documentation/asciidoc/computers/configuration/images/raspi-adv.png
  documentation/asciidoc/computers/configuration/images/raspi-config.png
  documentation/asciidoc/computers/configuration/images/raspi-display.png
  documentation/asciidoc/computers/configuration/images/raspi-interface.png
  documentation/asciidoc/computers/configuration/images/raspi-l18n.png
  documentation/asciidoc/computers/configuration/images/raspi-perf.png
  documentation/asciidoc/computers/configuration/images/raspi-system.png
  documentation/asciidoc/computers/configuration/images/wifi2.png
Labels: documentation, bookworm 🐛

#3110 Updated display configuration instructions for Bookworm changes
  documentation/asciidoc/computers/legacy_config_txt/video.adoc
  documentation/asciidoc/computers/raspberry-pi/display-parallel-interface.adoc
Labels: bookworm 🐛

#3087 Added whitepapers
  documentation/asciidoc/accessories/display/display_intro.adoc
  documentation/asciidoc/computers/compute-module/cm-emmc-flashing.adoc
  documentation/asciidoc/computers/compute-module/datasheet.adoc
  documentation/asciidoc/computers/config_txt/overclocking.adoc
  documentation/asciidoc/computers/configuration/hdmi-config.adoc
  documentation/asciidoc/computers/os/updating.adoc
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
  documentation/asciidoc/computers/raspberry-pi/display-parallel-interface.adoc
  documentation/asciidoc/computers/raspberry-pi/power-supplies.adoc
  documentation/asciidoc/computers/raspberry-pi/raspberry-pi-compliance.adoc
  documentation/asciidoc/computers/raspberry-pi/raspberry-pi-industrial.adoc
  documentation/asciidoc/microcontrollers/rp2040/rp2040_based_boards.adoc
  documentation/asciidoc/microcontrollers/rp2040/technical_specification.adoc
Labels: enhancement, documentation

#3112 Updated to reflect journalctl
  documentation/asciidoc/computers/configuration/securing-the-raspberry-pi.adoc
  documentation/asciidoc/computers/remote-access/network-boot-raspberry-pi.adoc
  documentation/asciidoc/computers/remote-access/secure-shell-passwordless.adoc
Labels: bookworm 🐛

#3114 Re-removed re-added compositor option
  documentation/asciidoc/computers/configuration/images/raspi-adv.png
  documentation/asciidoc/computers/configuration/raspi-config.adoc
Labels: bookworm 🐛

#3115 Updated performance config
  documentation/asciidoc/computers/configuration/images/raspi-perf.png
  documentation/asciidoc/computers/configuration/raspi-config.adoc
Labels: bookworm 🐛

#3116 Fix typo
  documentation/asciidoc/accessories/camera/synchronous_cameras.adoc
Labels: typo

#3118 Changed absolute link
  documentation/asciidoc/accessories/audio/getting_started.adoc
Labels: documentation

#3125 Update network configuration instructions for Bookworm
  documentation/asciidoc/computers/configuration/configuring-networking.adoc
Labels: bookworm 🐛, waiting for revisions

#3121 Touch display changes
  documentation/asciidoc/accessories/display.adoc
  documentation/asciidoc/accessories/display/display_intro.adoc
  documentation/asciidoc/accessories/display/images/display-rotation.png
  documentation/asciidoc/accessories/display/images/touch-GPIO.png
  documentation/asciidoc/accessories/display/legacy.adoc
  documentation/asciidoc/accessories/display/troubleshooting.adoc
Labels: documentation, bookworm 🐛, waiting for revisions

#3131 Fix Build HAT package name
  documentation/asciidoc/accessories/build-hat/py-installing-software.adoc
Labels: bug fix, bookworm 🐛

#3132 Fixing Touch Display documentation
  documentation/asciidoc/accessories/display/display_intro.adoc
Labels: bug fix

#3136 Update revision-codes.adoc for Pi5
  documentation/asciidoc/computers/raspberry-pi/revision-codes.adoc
Labels: pi5
