Repository raspberrypi/documentation, pull requests merged in 2023-10, with the labels that each got.

#3141 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: typo

#3142 Typos in using-python.adoc
  documentation/asciidoc/computers/os/using-python.adoc
Labels: typo

#3138 Add instructions to host a wireless network from a Raspberry Pi
  documentation/asciidoc/computers/configuration.adoc
  documentation/asciidoc/computers/configuration/host-wireless-network.adoc
  documentation/asciidoc/computers/configuration/images/create-hotspot-dialog.png
  documentation/asciidoc/computers/configuration/images/create-hotspot-network-menu.png
Labels: bookworm 🐛, waiting for revisions

#3033 Fix path for rpcbind defaults and fix rpcbind option
  documentation/asciidoc/computers/remote-access/nfs.adoc
Labels: bug fix, documentation

#3151 Remove GUI instructions so graphical users don't enable a hotspot and get stuck
  documentation/asciidoc/computers/configuration/host-wireless-network.adoc
Labels: enhancement, documentation, bookworm 🐛

#3157 Implement lurch's feedback on screen blanking updates
  documentation/asciidoc/computers/configuration/screensaver.adoc
Labels: bug fix, bookworm 🐛

#3160 Typos
  documentation/asciidoc/computers/os/using-python.adoc
Labels: typo

#3162 Typos
  documentation/asciidoc/computers/configuration/display-rotation.adoc
  documentation/asciidoc/computers/configuration/kernel-command-line-config.adoc
  documentation/asciidoc/computers/os/using-python.adoc
  documentation/asciidoc/computers/raspberry-pi/boot-net.adoc
Labels: typo

#3165 Spelling, grammar
  documentation/asciidoc/computers/os/using-python.adoc
Labels: typo

#3156 Update the Sense Hat documentation URL
  documentation/asciidoc/accessories/sense-hat/software.adoc
Labels: ready to merge, dependencies

#3166 Remove all mentions of wpa_supplicant file
  documentation/asciidoc/computers/configuration/boot_folder.adoc
  documentation/asciidoc/computers/configuration/headless.adoc
Labels: bug fix, bookworm 🐛

#3167 Remove style guide faux pas 'machine' term
  documentation/asciidoc/computers/configuration/headless.adoc
Labels: copy edit

#3169 Mention wpa_supplicant.conf in a NOTE
  documentation/asciidoc/computers/configuration/headless.adoc
Labels: documentation, bullseye

#3172 Add note about /boot/firmware
  documentation/asciidoc/computers/configuration/boot_folder.adoc
Labels: enhancement, documentation

#3173 Add cross-reference from the boot-folder section to kernel-command-line section
  documentation/asciidoc/computers/configuration/boot_folder.adoc
Labels: enhancement, documentation, copy edit

#3174 Small typo
  documentation/asciidoc/computers/configuration/screensaver.adoc
Labels: typo

#3180 Typos
  documentation/asciidoc/accessories/tv-hat/about-tv-hat.adoc
Labels: typo

#3185 Wait for element to load before scrolling
  jekyll-assets/_includes/scripts.html
Labels: bug fix, toolchain

#2963 Fixing adoc out-of-sequence warnings for pico-sdk
  scripts/transform_doxygen_html.py
Labels: paused, bug fix, toolchain

#3188 Update Compute Module IO Board camera configuration doc for Bookworm
  documentation/asciidoc/computers/camera/libcamera_apps_multicam.adoc
  documentation/asciidoc/computers/compute-module/cmio-camera.adoc
  documentation/asciidoc/computers/configuration/pin-configuration.adoc
Labels: camera 📷, bookworm 🐛

#3193 Removed legacy CM Camera info
  documentation/asciidoc/computers/compute-module/cm-peri-sw-guide.adoc
  documentation/asciidoc/computers/compute-module/cmio-camera.adoc
  documentation/asciidoc/computers/compute-module/cmio-display.adoc
  documentation/asciidoc/computers/configuration/pin-configuration.adoc
Labels: ready to merge, bug fix

#3194 Fix broken dt-blob command
  documentation/asciidoc/computers/configuration/pin-configuration.adoc
Labels: bug fix, urgent

#3195 Add J6 vertical example image for CM4 camera guide
  documentation/asciidoc/computers/compute-module/cmio-camera.adoc
  documentation/asciidoc/computers/compute-module/images/j6_vertical.jpg
Labels: enhancement, camera 📷

#3197 Update rtc.adoc
  documentation/asciidoc/computers/raspberry-pi-5/rtc.adoc
Labels: copy edit

#3202 CE. Many words.
  documentation/asciidoc/computers/raspberry-pi-5/power-supply.adoc
Labels: copy edit

#3201 Fixing some typos Liz missed
  documentation/asciidoc/computers/raspberry-pi-5/cooling.adoc
Labels: typo

#3203 Update about_rp1.adoc
  documentation/asciidoc/microcontrollers/rp1/about_rp1.adoc
Labels: copy edit

#3206 Typo
  documentation/asciidoc/accessories/display/display_intro.adoc
Labels: typo

#3211 Accidentally an extra word
  documentation/asciidoc/computers/getting-started/install.adoc
Labels: typo

#3216 Update power-supply.adoc : Typo
  documentation/asciidoc/computers/raspberry-pi-5/power-supply.adoc
Labels: typo

#3215 Update poe.adoc : Typo
  documentation/asciidoc/computers/raspberry-pi-5/poe.adoc
Labels: typo

#3214 Update pcie.adoc : Typo
  documentation/asciidoc/computers/raspberry-pi-5/pcie.adoc
Labels: typo

#3213 Update mipi.adoc : Typos
  documentation/asciidoc/computers/raspberry-pi-5/mipi.adoc
Labels: typo

#3212 Update cooling.adoc : Typos
  documentation/asciidoc/computers/raspberry-pi-5/cooling.adoc
Labels: typo

#3223 Fix typo + Use connector names
  documentation/asciidoc/computers/raspberry-pi-5/mipi.adoc
Labels: copy edit

#3226 bootloader-config: Bootloader configuration updates
  documentation/asciidoc/computers/compute-module/cm-emmc-flashing.adoc
  documentation/asciidoc/computers/configuration/boot_folder.adoc
  documentation/asciidoc/computers/configuration/raspi-config.adoc
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
  documentation/asciidoc/computers/raspberry-pi/boot-diagnostics-rpi4.adoc
  documentation/asciidoc/computers/raspberry-pi/boot-eeprom-rpi4.adoc
  documentation/asciidoc/computers/raspberry-pi/boot-msd.adoc
  documentation/asciidoc/computers/raspberry-pi/boot-net.adoc
  documentation/asciidoc/computers/raspberry-pi/boot-nvme.adoc
  documentation/asciidoc/computers/raspberry-pi/bootflow-2711.adoc
  documentation/asciidoc/computers/raspberry-pi/bootmodes.adoc
  documentation/asciidoc/computers/raspberry-pi/otp-bits.adoc
  documentation/asciidoc/computers/remote-access/network-boot-raspberry-pi.adoc
Labels: pi5 5️⃣

#3228 device-tree: Describe the new DT /power nodes and rpi-duid
  documentation/asciidoc/computers/configuration/device-tree.adoc
Labels: pi5 5️⃣

#3229 Fix typo in power-supply.adoc
  documentation/asciidoc/computers/raspberry-pi-5/power-supply.adoc
Labels: typo

#3233 Pi5 clocks gpu memory
  documentation/asciidoc/computers/config_txt/boot.adoc
  documentation/asciidoc/computers/config_txt/conditional.adoc
  documentation/asciidoc/computers/config_txt/overclocking.adoc
  documentation/asciidoc/computers/config_txt/video.adoc
  documentation/asciidoc/computers/legacy_config_txt/memory.adoc
  documentation/asciidoc/computers/raspberry-pi/boot-eeprom-rpi4.adoc
  documentation/asciidoc/computers/raspberry-pi/bootflow-2711.adoc
  documentation/asciidoc/computers/raspberry-pi/bootflow-legacy.adoc
  documentation/asciidoc/computers/raspberry-pi/bootmodes.adoc
  documentation/asciidoc/computers/raspberry-pi/frequency-management.adoc
Labels: enhancement, documentation, pi5 5️⃣

#3234 Update NFS root setup instructions for Bookworm
  documentation/asciidoc/computers/remote-access/network-boot-raspberry-pi.adoc
Labels: bookworm 🐛

#3236 Camera doc updates
  documentation/asciidoc/computers/camera/libcamera_apps_building.adoc
  documentation/asciidoc/computers/camera/libcamera_differences.adoc
  documentation/asciidoc/computers/camera/libcamera_hello.adoc
  documentation/asciidoc/computers/camera/libcamera_options_common.adoc
Labels: bug fix, documentation, camera 📷

#3242 Update about_rp1.adoc
  documentation/asciidoc/microcontrollers/rp1/about_rp1.adoc
Labels: documentation

#3244 Update bcm2711-bootloader.adoc : Typos
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
Labels: typo

#3245 Update boot.adoc : Typo
  documentation/asciidoc/computers/config_txt/boot.adoc
Labels: typo

#3246 vcgencmd updated repo location
  documentation/asciidoc/computers/os/graphics-utilities.adoc
Labels: documentation, bookworm 🐛

#3247 Update display_intro.adoc for updated touch overlay instructions
  documentation/asciidoc/accessories/display/display_intro.adoc
Labels: bug fix, documentation, bookworm 🐛

#3248 Update bootmodes.adoc
  documentation/asciidoc/computers/raspberry-pi/bootmodes.adoc
Labels: bug fix

#3251 Update location of bootcode.bin
  documentation/asciidoc/computers/raspberry-pi/bootmodes.adoc
Labels: bug fix
