Repository raspberrypi/documentation, pull requests merged in 2024-01, with the labels that each got.

#3340 Update PCIe
  documentation/asciidoc/computers/raspberry-pi-5/pcie.adoc
Labels: enhancement, documentation, pi5 5️⃣

#3338 Update rpicam_apps_packages.adoc - Refer to libcamera-dev
  documentation/asciidoc/computers/camera/rpicam_apps_building.adoc
  documentation/asciidoc/computers/camera/rpicam_apps_packages.adoc
Labels: documentation, camera 📷

#3345 Improve documentation on raw camera mode selection for Pi 5
  documentation/asciidoc/computers/camera/rpicam_options_common.adoc
  documentation/asciidoc/computers/camera/rpicam_raw.adoc
Labels: camera 📷

#3346 Remove duplicated word word
  documentation/asciidoc/computers/config_txt/common.adoc
Labels: typo

#3347 Pi5 otp doc update
  documentation/asciidoc/computers/raspberry-pi/otp-bits.adoc
  documentation/asciidoc/computers/raspberry-pi/raspberry-pi-industrial.adoc
Labels: pi5 5️⃣

#3354 Update revision-codes.adoc with v1.4 3B+
  documentation/asciidoc/computers/raspberry-pi/revision-codes.adoc
Labels: bug fix, documentation

#3355 Update revision-codes.adoc to add 3A+ v1.1
  documentation/asciidoc/computers/raspberry-pi/revision-codes.adoc
Labels: bug fix, documentation

#3358 Clarify touch display rotation instructions
  documentation/asciidoc/accessories/display/display_intro.adoc
Labels: documentation

#3357 Update headless.adoc: Add details about allowed symbols for the username
  documentation/asciidoc/computers/configuration/headless.adoc
Labels: documentation

#3368 Correct password length limit
  documentation/asciidoc/computers/configuration/headless.adoc
Labels: typo

#3375 Update compute module display doc to use 'new' KMS driver
  documentation/asciidoc/accessories/display/legacy.adoc
  documentation/asciidoc/computers/compute-module/cm-emmc-flashing.adoc
  documentation/asciidoc/computers/compute-module/cmio-camera.adoc
  documentation/asciidoc/computers/compute-module/cmio-display.adoc
  documentation/asciidoc/computers/compute-module/images/CMIO-Cam-Disp-Example.jpg
  documentation/asciidoc/computers/compute-module/images/CMIO-Cam-Disp-GPIO.jpg
Labels: documentation, update

#3360 CE for style, grammar, etc.
  documentation/asciidoc/computers/getting-started/setting-up.adoc
Labels: copy edit

#3362 CE for sense/style
  documentation/asciidoc/computers/raspberry-pi-5/power-supply.adoc
Labels: copy edit

#3363 CE. Mostly commas.
  documentation/asciidoc/computers/raspberry-pi-5/cooling.adoc
Labels: copy edit

#3364 Update display_intro.adoc
  documentation/asciidoc/accessories/display/display_intro.adoc
Labels: copy edit

#3365 CE for style/sense
  documentation/asciidoc/computers/raspberry-pi-5/pcie.adoc
Labels: copy edit

#3366 CE, mostly punctuation
  documentation/asciidoc/computers/raspberry-pi-5/mipi.adoc
Labels: copy edit

#3367 Wi-Fi->WiFi
  documentation/asciidoc/computers/getting-started/configuring.adoc
Labels: typo

#3370 CE
  documentation/asciidoc/computers/os/updating.adoc
Labels: copy edit

#3371 CE
  documentation/asciidoc/computers/os/playing-audio-and-video.adoc
Labels: copy edit

#3372 CE
  documentation/asciidoc/computers/os/using-webcams.adoc
Labels: copy edit

#3373 Copy edit
  documentation/asciidoc/computers/os/graphics-utilities.adoc
Labels: copy edit

#3374 CE
  documentation/asciidoc/computers/os/accessibility.adoc
Labels: copy edit

#3377 Copy edit
  documentation/asciidoc/computers/os/using-gpio.adoc
Labels: copy edit

#3380 CE
  documentation/asciidoc/computers/configuration/headless.adoc
Labels: copy edit

#3384 CE
  documentation/asciidoc/computers/configuration/display-resolution.adoc
Labels: copy edit

#3378 CE
  documentation/asciidoc/computers/configuration/raspi-config.adoc
Labels: copy edit

#3381 CE
  documentation/asciidoc/computers/configuration/host-wireless-network.adoc
Labels: copy edit

#3382 Capitalisation
  documentation/asciidoc/computers/configuration/use-a-proxy.adoc
Labels: typo

#3383 CE
  documentation/asciidoc/computers/configuration/hdmi-config.adoc
Labels: copy edit

#3386 CE
  documentation/asciidoc/computers/configuration/external-storage.adoc
Labels: copy edit

#3388 CE, bullet point hell
  documentation/asciidoc/computers/configuration/pin-configuration.adoc
Labels: bug fix, copy edit

#3391 CE
  documentation/asciidoc/computers/configuration/kernel-command-line-config.adoc
Labels: copy edit

#3390 CE
  documentation/asciidoc/computers/configuration/device-tree.adoc
Labels: copy edit

#3393 Capitalisation
  documentation/asciidoc/computers/configuration/led_blink_warnings.adoc
Labels: copy edit

#3397 Add information about HAT connection precautions when connected to power
  documentation/asciidoc/computers/raspberry-pi-5/introduction.adoc
Labels: pi5 5️⃣, update

#3395 Standardize language referring to JST-SH connectors on RPis and peripherals
  documentation/asciidoc/computers/raspberry-pi-5/cooling.adoc
  documentation/asciidoc/computers/raspberry-pi-5/rtc.adoc
  documentation/asciidoc/computers/raspberry-pi-5/uart.adoc
  documentation/asciidoc/microcontrollers/debug-probe/getting-started.adoc
  documentation/asciidoc/microcontrollers/debug-probe/introduction.adoc
Labels: bug fix

#3412 CE, added Pi 5 detail
  documentation/asciidoc/computers/config_txt/video.adoc
Labels: copy edit

#3420 CE (style)
  documentation/asciidoc/computers/legacy_config_txt/memory.adoc
Labels: copy edit

#3418 CE
  documentation/asciidoc/computers/legacy_config_txt/overclocking.adoc
Labels: copy edit

#3417 Capitalisation, and ARM-->Arm
  documentation/asciidoc/computers/legacy_config_txt/gpio.adoc
Labels: typo

#3416 CE for style and readability
  documentation/asciidoc/computers/legacy_config_txt/boot.adoc
Labels: copy edit

#3415 CE for style/sense
  documentation/asciidoc/computers/legacy_config_txt/legacy.adoc
Labels: copy edit

#3414 CE
  documentation/asciidoc/computers/config_txt/camera.adoc
Labels: copy edit

#3411 Capitalisation
  documentation/asciidoc/computers/config_txt/codeclicence.adoc
Labels: typo

#3410 Changed a capital O to a lower-case o.
  documentation/asciidoc/computers/config_txt/memory.adoc
Labels: typo

#3409 CE, style, wording
  documentation/asciidoc/computers/config_txt/conditional.adoc
Labels: copy edit

#3408 CE
  documentation/asciidoc/computers/config_txt/overclocking.adoc
Labels: copy edit

#3403 CE
  documentation/asciidoc/computers/config_txt/boot.adoc
Labels: copy edit

#3402 Capitalisation
  documentation/asciidoc/computers/config_txt/audio.adoc
Labels: typo

#3401 CE
  documentation/asciidoc/computers/config_txt/common.adoc
Labels: copy edit

#3400 CE
  documentation/asciidoc/computers/config_txt/autoboot.adoc
Labels: copy edit

#3399 CE
  documentation/asciidoc/computers/config_txt/what_is_config_txt.adoc
Labels: copy edit

#3396 Capitalisation
  documentation/asciidoc/computers/configuration/screensaver.adoc
Labels: typo

#3394 CE
  documentation/asciidoc/computers/configuration/securing-the-raspberry-pi.adoc
Labels: copy edit

#3421 CE
  documentation/asciidoc/computers/legacy_config_txt/video.adoc
Labels: copy edit

#3422 Fixed up all the stuff that wasn't links
  documentation/asciidoc/computers/legacy_config_txt/pi4-hdmi.adoc
Labels: copy edit

#3423 CE
  documentation/asciidoc/computers/linux_kernel/about-kernel.adoc
Labels: copy edit

#3424 CE
  documentation/asciidoc/computers/linux_kernel/building.adoc
Labels: copy edit

#3425 CE, style
  documentation/asciidoc/computers/linux_kernel/configuring.adoc
Labels: copy edit

#3426 CE
  documentation/asciidoc/computers/linux_kernel/patching.adoc
Labels: copy edit

#3427 CE
  documentation/asciidoc/computers/linux_kernel/headers.adoc
Labels: copy edit

#3428 CE
  documentation/asciidoc/computers/camera/camera_usage.adoc
Labels: copy edit

#3429 CE
  documentation/asciidoc/computers/camera/rpicam_apps_intro.adoc
Labels: copy edit

#3430 CE
  documentation/asciidoc/computers/camera/rpicam_apps_getting_started.adoc
Labels: copy edit

#3431 CE
  documentation/asciidoc/computers/camera/rpicam_hello.adoc
Labels: copy edit

#3432 CE
  documentation/asciidoc/computers/camera/rpicam_jpeg.adoc
Labels: copy edit

#3433 CE
  documentation/asciidoc/computers/camera/rpicam_vid.adoc
Labels: copy edit

#3434 H.264 clarification, CE
  documentation/asciidoc/computers/camera/rpicam_apps_libav.adoc
Labels: copy edit

#3435 CE
  documentation/asciidoc/computers/camera/rpicam_raw.adoc
Labels: copy edit

#3436 CE
  documentation/asciidoc/computers/camera/rpicam_detect.adoc
Labels: copy edit

#3439 Update SSH instructions to include new imager keygen instructions
  documentation/asciidoc/computers/remote-access.adoc
  documentation/asciidoc/computers/remote-access/secure-shell-from-unix.adoc
  documentation/asciidoc/computers/remote-access/secure-shell-from-windows10.adoc
  documentation/asciidoc/computers/remote-access/secure-shell-passwordless.adoc
  documentation/asciidoc/computers/remote-access/secure-shell.adoc
  documentation/asciidoc/computers/remote-access/ssh-client.adoc
  documentation/asciidoc/computers/remote-access/ssh-passwordless.adoc
  documentation/asciidoc/computers/remote-access/ssh-server.adoc
Labels: update

#3438 CE
  documentation/asciidoc/computers/camera/rpicam_options_common.adoc
Labels: copy edit

#3440 Update rpicam-apps git repository to correct URL
  documentation/asciidoc/computers/camera/rpicam_apps_intro.adoc
Labels: bug fix

#3441 CE for style and consistency
  documentation/asciidoc/computers/camera/rpicam_options_still.adoc
Labels: copy edit

#3452 Remove rogue plus signs that render on page
  documentation/asciidoc/computers/configuration/pin-configuration.adoc
Labels: bug fix

#3450 Add margin for nested code blocks
  jekyll-assets/css/style.css
Labels: bug fix, toolchain

#3454 Better consistency with SWCLK usage in the rest of the docs
  documentation/asciidoc/microcontrollers/debug-probe/getting-started.adoc
Labels: bug fix

#3442 CE (style, punctuation)
  documentation/asciidoc/computers/camera/rpicam_options_vid.adoc
Labels: copy edit

#3443 CE: style, spot of sentence restructuring
  documentation/asciidoc/computers/camera/libcamera_differences.adoc
Labels: copy edit

#3444 CE
  documentation/asciidoc/computers/camera/rpicam_apps_post_processing.adoc
Labels: copy edit

#3445 CE
  documentation/asciidoc/computers/camera/rpicam_apps_post_processing_opencv.adoc
Labels: copy edit

#3465 CE
  documentation/asciidoc/computers/raspberry-pi/raspberry-pi-compliance.adoc
Labels: copy edit

#3466 CE, added copy about cooling Pi 5
  documentation/asciidoc/computers/raspberry-pi/frequency-management.adoc
Labels: copy edit

#3472 Replace pi_plugs Display GPIO image with something that matches the adjacent photo
  documentation/asciidoc/accessories/display/images/pi_plugs.png
Labels: bug fix

#3447 CE
  documentation/asciidoc/computers/camera/rpicam_apps_multicam.adoc
Labels: copy edit

#3448 CE
  documentation/asciidoc/computers/camera/rpicam_apps_packages.adoc
Labels: copy edit

#3449 CE
  documentation/asciidoc/computers/camera/rpicam_apps_building.adoc
Labels: copy edit

#3453 CE
  documentation/asciidoc/computers/camera/libcamera_python.adoc
Labels: copy edit

#3456 CE
  documentation/asciidoc/computers/camera/libcamera_known_issues.adoc
Labels: copy edit

#3457 CE
  documentation/asciidoc/computers/camera/rpicam_apps_getting_help.adoc
Labels: copy edit

#3458 CE
  documentation/asciidoc/computers/camera/timelapse.adoc
Labels: copy edit

#3460 CE
  documentation/asciidoc/computers/camera/qt.adoc
Labels: copy edit

#3461 CE
  documentation/asciidoc/computers/camera/v4l2.adoc
Labels: copy edit

#3462 CE
  documentation/asciidoc/computers/camera/csi-2-usage.adoc
Labels: copy edit

#3463 CE
  documentation/asciidoc/computers/os/using-gpio.adoc
Labels: copy edit

#3464 CE
  documentation/asciidoc/computers/raspberry-pi/raspberry-pi-schematics.adoc
Labels: copy edit

#3468 CE
  documentation/asciidoc/computers/raspberry-pi/boot-diagnostics-rpi4.adoc
Labels: copy edit

#3469 CE
  documentation/asciidoc/computers/raspberry-pi/bootmodes.adoc
Labels: copy edit

#3470 CE
  documentation/asciidoc/computers/raspberry-pi/bootflow-legacy.adoc
Labels: copy edit

#3471 CE
  documentation/asciidoc/computers/raspberry-pi/bootflow-2711.adoc
Labels: copy edit

#3475 CE
  documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc
Labels: copy edit

#3481 CE
  documentation/asciidoc/computers/raspberry-pi/boot-http.adoc
Labels: copy edit

#3480 CE
  documentation/asciidoc/computers/raspberry-pi/boot-nvme.adoc
Labels: copy edit

#3478 CE
  documentation/asciidoc/computers/raspberry-pi/boot-gpio.adoc
Labels: copy edit

#3477 CE
  documentation/asciidoc/computers/raspberry-pi/boot-msd.adoc
Labels: copy edit

#3476 CE
  documentation/asciidoc/computers/raspberry-pi/boot-usb.adoc
Labels: copy edit

#3484 CE
  documentation/asciidoc/computers/raspberry-pi/gpio-on-raspberry-pi.adoc
Labels: copy edit

#3482 CE: Sentence-case titles in display-parallel-interface.adoc
  documentation/asciidoc/computers/raspberry-pi/display-parallel-interface.adoc
Labels: copy edit

#3487 CE
  documentation/asciidoc/computers/raspberry-pi/gpio-pad-controls.adoc
Labels: copy edit

#3488 CE
  documentation/asciidoc/computers/raspberry-pi/raspberry-pi-industrial.adoc
Labels: copy edit

#3489 CE
  documentation/asciidoc/computers/raspberry-pi/otp-bits.adoc
Labels: copy edit

#3493 CE
  documentation/asciidoc/computers/raspberry-pi/spi-bus-on-raspberry-pi.adoc
Labels: copy edit

#3501 CE
  documentation/asciidoc/computers/compute-module/cmio-camera.adoc
Labels: copy edit

#3499 CE
  documentation/asciidoc/computers/compute-module/cm-peri-sw-guide.adoc
Labels: copy edit

#3498 CE
  documentation/asciidoc/computers/compute-module/cm-emmc-flashing.adoc
Labels: copy edit

#3497 Capitalisation
  documentation/asciidoc/computers/compute-module/designfiles.adoc
Labels: typo

#3496 CE
  documentation/asciidoc/computers/compute-module/datasheet.adoc
Labels: copy edit

#3494 CE
  documentation/asciidoc/computers/raspberry-pi/usb-bus-on-raspberry-pi.adoc
Labels: copy edit

#3502 Fix EOL date for CM3+
  documentation/asciidoc/computers/compute-module/datasheet.adoc
Labels: bug fix

#3508 Improve wording, content, and organisation of network boot section
  documentation/asciidoc/computers/raspberry-pi.adoc
  documentation/asciidoc/computers/raspberry-pi/boot-net.adoc
  documentation/asciidoc/computers/raspberry-pi/eeprom-bootloader.adoc
Labels: copy edit

#3521 Update rpicam_apps_intro.adoc Added clarification for debian version and rpicam-apps vs libcamera-app.
  documentation/asciidoc/computers/camera/rpicam_apps_intro.adoc
Labels: documentation
