Repository raspberrypi/documentation, pull requests merged in 2024-03, with the labels that each got.

#3503 Proposing changes to terminology and lens FOV as per #3255
  documentation/asciidoc/accessories/camera/lens.adoc
Labels: camera 📷

#3550 Mention cd firmware has no debug logging
  documentation/asciidoc/computers/config_txt/boot.adoc
  documentation/asciidoc/computers/configuration/boot_folder.adoc
Labels: update

#3551 Add fallback to handle new doxygen helper files
  scripts/transform_doxygen_html.py
Labels: toolchain

#3549 Update libcamera build instructions
  documentation/asciidoc/computers/camera/rpicam_apps_building.adoc
  documentation/asciidoc/computers/camera/rpicam_apps_packages.adoc
Labels: camera 📷, update

#3558 Remove explicit mention that RealVNC is not supported
  documentation/asciidoc/computers/remote-access/vnc.adoc
Labels: bookworm 🐛

#3560 Update licence keys section for pi 5
  documentation/asciidoc/computers/config_txt/codeclicence.adoc
Labels: update

#3561 Add node explaining that no Pi models support video over usb-c
  documentation/asciidoc/computers/getting-started/setting-up.adoc
Labels: enhancement

#3564 Update regex to use valid escape sequences
  README.md
  scripts/create_build_adoc.py
  scripts/create_build_adoc_include.py
Labels: bug fix

#3565 Update version number of debug probe firmware and improve copy of both versions of instructions
  documentation/asciidoc/microcontrollers/debug-probe/updating-firmware.adoc
  documentation/asciidoc/microcontrollers/raspberry-pi-pico/utilities.adoc
Labels: enhancement

#3567 Update network install section to include Pi 5
  documentation/asciidoc/computers/getting-started/install.adoc
Labels: pi5 5️⃣, update

#3571 Correct plural in boot-eeprom-rpi4
  documentation/asciidoc/computers/raspberry-pi/boot-eeprom-rpi4.adoc
Labels: copy edit
